"""Add Politica model for Biblioteca Inteligente

Revision ID: 0606361191b0
Revises: 5b6a5f24967e
Create Date: 2026-07-07 06:17:25.472815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0606361191b0'
down_revision = '5b6a5f24967e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('resumen_ejecutivo', sa.Text(), nullable=False),
    sa.Column('problema', sa.Text(), nullable=True),
    sa.Column('objetivos', sa.Text(), nullable=True),
    sa.Column('poblacion_objetivo', sa.String(length=300), nullable=True),
    sa.Column('normatividad', sa.Text(), nullable=True),
    sa.Column('cronologia', sa.Text(), nullable=True),
    sa.Column('entidades_responsables', sa.String(length=500), nullable=True),
    sa.Column('indicadores', sa.Text(), nullable=True),
    sa.Column('presupuesto', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('documentos', sa.Text(), nullable=True),
    sa.Column('ods_relacionados', sa.String(length=200), nullable=True),
    sa.Column('alcance', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('politicas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_politicas_sector_id'), ['sector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_politicas_titulo'), ['titulo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_politicas_titulo'))
        batch_op.drop_index(batch_op.f('ix_politicas_sector_id'))

    op.drop_table('politicas')
    # ### end Alembic commands ###
