"""initial migration

Revision ID: 6ee3994227d4
Revises: 
Create Date: 2026-06-30 21:12:30.575801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee3994227d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participaciones_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_participaciones_departamento'), ['departamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_participaciones_sector_prioritario_id'), ['sector_prioritario_id'], unique=False)
        batch_op.drop_column('palabras_clave')
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('palabras_clave', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_participaciones_sector_prioritario_id'))
        batch_op.drop_index(batch_op.f('ix_participaciones_departamento'))
        batch_op.drop_index(batch_op.f('ix_participaciones_created_at'))

    # ### end Alembic commands ###
